### ISSUE TITLE
Some code problem 

### ISSUE THREAD

**Issue by Lance0724** [olliw42/mLRS#1]
1. There are so many hard code local path(like "C:/Users/Olli/Documents/GitHub/.....") in the project file ( ".XXXXX" file  like .project/.cproject)
2. Implement the method of the class in the header file (like rxstats.h)
3. Define global variables in header files( in common.h , the section: "Common Variables "  )

**Comment by Lance0724** [comment]
I`m The First ~ 😄

**Comment by olliw42** [comment]
many thx

yeah, I'm not really happy with STM32CubeIDE ... and I use it only for short ... I noted these hard coded paths too, but I frankly have no idea how to overcome that 

any help of how to get STM32CubeIde to behave well such that it can be transferred would be massively appreciated

**Comment by olliw42** [comment]
@Lance0724 
solved 1. by improving the setup procedure. Points 2. & 3. are really not code problems but rather taste. So I close the issue. Please do not hesitate to reopen if you feel it needs further consideration.

**Comment by Lance0724** [comment]
<img width="548" alt="262db194fd812c4f1ca5f33867d811c" src="https://user-images.githubusercontent.com/7992946/150347443-c34b6416-9c5a-49d8-b02f-69339fb9fe54.png">

Build Finished. 😄

**Comment by olliw42** [comment]
great! many thx for the feedback
