### ISSUE TITLE
FLRC mode issues to work out

### ISSUE THREAD

**Issue by olliw42** [olliw42/mLRS#101]
title says it. Todos:

- [ ] LQ is "bad"
- [x] bind seems to not work

**Comment by jlpoltrack** [comment]
@olliw42 
Re: Binding, (untested) PR here: https://github.com/olliw42/mLRS/pull/102

**Comment by jlpoltrack** [comment]
Quick thoughts on LQ:

- Changing coding rate to 1/2 w/ .65 @ 125 Hz showed better LQ for me.  This is a bit aggressive with 1.7 ms overheard.  So nicer options would be 111 Hz or 100 Hz.
- Another option would be to use 1.04 w/ 1/2 coding rate, this would allow for 167 Hz and be more tolerant of frequency error.  Downside here is that there would probably have to be some considerations for frequency range and possibly channel spacing.

**Comment by olliw42** [comment]
merged as default on option

THX @jlpoltrack for adding this option!
