### ISSUE TITLE
run_copy_st_drivers.py breaks when path contains a space

### ISSUE THREAD

**Issue by jlpoltrack** [olliw42/mLRS#127]
On Windows, if folder within path contains a space the script fails to copy the drivers as expected.

Renaming the folder with a space resolves.

**Comment by olliw42** [comment]
many thx for the report.
I confirm the issue,
it appears top be a regression of changes i made recently (not happening in older versions)
pushed a correction, maybe you can test/confirm it's all good now

**Comment by jlpoltrack** [comment]
Looks good now - thanks.
