### ISSUE TITLE
Firmware for elrs_bl, how to compile firmware for elrs_bl bootloader?

### ISSUE THREAD

**Issue by Vldbas** [olliw42/mLRS#131]
It’s not written anywhere how to configure the .elrs firmware. I found some mention in the code, but perhaps there is some special solution? I have installed elrs_bl my r9m.

**Comment by olliw42** [comment]
@Vldbas 
welcome

first off, the github issues are NOT for support questions but to report issues with the code. This here is, if I'm not mistaken, a support question, so please consider using the discussion places, i.e., rcgroups thread or discord channel. Thx.

you find info on this in the documentation, https://github.com/olliw42/mLRS-docu/blob/master/docs/FRSKY_R9.md. If not pl do not hesitate to join the discussion places.

closing.
