### ISSUE TITLE
sbus RSSI out on PWM channel doesn't work

### ISSUE THREAD

**Issue by Imen-D** [olliw42/mLRS#14]
Hi, Olliw
I set RSSI out on channel 12, but can't get it working, PWM on channel 12 didn't change at all.

Do you think is because of this ? :
void OutBase::Configure(uint8_t new_config, uint8_t new_rssi_channel, uint8_t new_failsafe_mode)
{
    rssi_channel = new_rssi_channel;
    if (rssi_channel <= RC_DATA_LEN) rssi_channel = 0;

**Comment by olliw42** [comment]
oh ... yes ... this happens then one is adding a line of code without explicit test LOL

corrected
and I've also changed a bit to get data consistency

many thx !!
