### ISSUE TITLE
RX failsafe flag is still exist on BF 4.2.11

### ISSUE THREAD

**Issue by Imen-D** [olliw42/mLRS#15]
Hi Olliw, I can't regain control on BF after failsafe, even if we have solid link.
Do you think frame_missed is need to clear ?

**Comment by olliw42** [comment]
ohje, how could this happen
yes, absolutely, frame_missed should be of course cleared ... this little line must have gone lost at some point
well spotted
MANY THX 
I have pushed a correction, so am closing. thx again
