### ISSUE TITLE
regression on tx-easysolder-E77-E22-dual-wle5cc

### ISSUE THREAD

**Issue by ecarjat** [olliw42/mLRS#204]
When uploading pre-release [tx-easysolder-E77-E22-dual-wle5cc-diversity-v1.2.04.hex](https://github.com/olliw42/mLRS/blob/main/firmware/pre-release-stm32/tx-easysolder-E77-E22-dual-wle5cc-diversity-v1.2.04.hex) to a DIY easysolder board (pre-xtal version) the board is no longer working, the green led is faintly lit and the yellow led is not lit at all.
The issue is reproduced with [tx-easysolder-E77-E22-dual-wle5cc-v1.2.04.hex](https://github.com/olliw42/mLRS/blob/main/firmware/pre-release-stm32/tx-easysolder-E77-E22-dual-wle5cc-v1.2.04.hex). The board works fine with release 1.2.0.
I have also reproduced the issue with a locally compiled version with #define MLRS_FEATURE_E77_XTAL commented out.

**Comment by olliw42** [comment]
many thx for the report

I won't rule out we made a mistake, but just to double check:
you are saying "pre-xtal version" and "works fine with 1.2.0", is it possible you're mixing up the meaning? xtal means old E77 with old-fashion xtal. If your E77 has an xtal (not txco), which it appears to have from your text, this means, in the current firmware version you need to use a file with -xtal in the name.
