### ISSUE TITLE
List of PA/LNA for targets

### ISSUE THREAD

**Issue by olliw42** [olliw42/mLRS#205]
not an issue
I'd like to compile a list of the PA/LNAs used by the various targets. It's first to keep track, but also becasue I would like to better separate this out in the hal files.

- E28-2G4M27S/SX: SKY85321-11
- FRM303: SKY66312-11
- ELRS Generic 2400 PA ESP8285: AT2401C
- ELRS Generic 2400 D PA ESP8285: SE2431L
- RadioMaster RP4TD: AT2401C
- FrSky R9M: SKY65111-384LF
- FrSky R9M Lite Pro: SKY65111-384LF
- ELRS Generic 900 TD PA ESP32: SKY66319-11
- RadioMaster Bandit Micro: SE2435L

to be determined:

- ELRS Generic 900 PA ESP8266: ??
- BetaFpv 1W Micro Tx module: ??

**Comment by jlpoltrack** [comment]
> * ELRS Generic 2400 D PA ESP8285: ??

SE2431L

> * ELRS Generic 2400 PA ESP8285: ??

AT2401C

> * RadioMaster RP4TD: ??

AT2401C

**Comment by olliw42** [comment]
THX!

you could double check/confrim some of the others I did already?

**Comment by olliw42** [comment]
I'm a bit wondering on which occasion I stumbled over the SE2431L before ... its datasheet is for >2 years in the doc folder ...

**Comment by jlpoltrack** [comment]
> you could double check/confrim some of the others I did already?

The others look good to me.  Suppose I could note that there are two E28 variants (mLRS designs use the 27 variant):

1. E28-2G4M27S/SX: SKY85321-11
2. E28-2G4M22S: AT2401C

**Comment by jlpoltrack** [comment]
> * ELRS Generic 900 TD PA ESP32

Skyworks 66421-11

**Comment by olliw42** [comment]
@jlpoltrack I've tried to compile things into a hal-power-pa.h hal file for later use, but it's pretty incomplete, and uncovers some inconsistencies. Thoughts? Corrections?

[hal-power-pa.zip](https://github.com/user-attachments/files/16303750/hal-power-pa.zip)
