### ISSUE TITLE
Lua TX12

### ISSUE THREAD

**Issue by Dwakener** [olliw42/mLRS#207]
Good afternoon. TX12 hardware gets stuck loading LUA.  TX = E77-MBLKit-wle5cc

**Comment by Dwakener** [comment]
10:15:51 : Data read successfully
10:15:51 : Time elapsed during the read operation is: 00:00:02.783
10:16:10 : Read File: C:\mlrs\firmware\pre-release-stm32\tx-E77-MBLKit-wle5cc-400-v1.2.04.hex
10:16:10 : Number of segments: 1
10:16:10 : segment[0]: address= 0x8000000, size= 0x13268
10:16:17 : Memory Programming ...
10:16:17 : Opening and parsing file: tx-E77-MBLKit-wle5cc-400-v1.2.04.hex
10:16:17 :   File          : tx-E77-MBLKit-wle5cc-400-v1.2.04.hex
10:16:17 :   Size          : 76.60 KB 
10:16:17 :   Address       : 0x08000000 
10:16:17 : Erasing memory corresponding to segment 0:
10:16:17 : Erasing internal memory sectors [0 38]
10:16:18 : Download in Progress:
10:16:19 : File download complete
10:16:19 : Time elapsed during download operation: 00:00:02.208

**Comment by Dwakener** [comment]
![photo_2024-07-10_12-47-52](https://github.com/olliw42/mLRS/assets/53927462/b9893e3f-c666-4742-9d38-d87eec32ae6f)
![photo_2024-07-10_12-47-49](https://github.com/olliw42/mLRS/assets/53927462/4760b497-4933-4e3b-a378-e2b565b19209)

**Comment by olliw42** [comment]
many thx for the report
the lua support on bw radios is always a bit of an issue, since no dev has such a radio. And there are so many of them.

yo are running mLRS-bw, and not mLRS, right?

what firmware is your radio on? You need latest OpenTx or latest EdgeTx. 
do you have any other script or similar running, which would eat memory away?

**Comment by Dwakener** [comment]
Expressel modules work stably. Regular script mLRS restarts the equipment,  mLRS-bw the loading text hangs and nothing happens. Out of curiosity I watched the broadcast, there is silence on 433MHZ

**Comment by Dwakener** [comment]
I also looked at the jumper on the antenna, you didn’t have it in the pictures, here it is
![изображение](https://github.com/olliw42/mLRS/assets/53927462/7447d4a5-a1c7-46cf-b628-dfb6dc8f9a42)

**Comment by Dwakener** [comment]
EDGETX-TX12MK2 2.8.0 CFGV 221

**Comment by olliw42** [comment]
upgrade your edgetx to latest, it's known t not work on that old version

**Comment by Dwakener** [comment]
edgetx-firmware-v2.10.2 helped !!!

**Comment by olliw42** [comment]
great
glad to hear it works

two general comments pl
- this was obviously a support topic and not an issue report. The github repo is NOT for support. For support pl consider going to the support channels next time (rcgroups thread or discord channel)
- consider readin and rereading the docs carefully in case of issues. One would have found the comment on the edgetx version there :) I mean, you sure are most welcome to raise your questions and ask for help, but it may safe you your time :)
