### ISSUE TITLE
R9 hardware: users should be warned to flash latest version of ELRS bootloader

### ISSUE THREAD

**Issue by jiri-jirus** [olliw42/mLRS#216]
users should be warned to flash latest version of ELRS bootloader. because when they flashed ELRS on their R9 stuff, they may have used 0.5.3 bootloader, which does not work with mLRS.

**Comment by jiri-jirus** [comment]
this is serial output of RX module when flashed by old bootloaders and uploaded mLRS. 
![obrazek](https://github.com/user-attachments/assets/a055c898-3c77-42c6-aa4b-89b33a9a2646)

**Comment by olliw42** [comment]
@brad112358

**Comment by olliw42** [comment]
appears to be resolved
closing
