### ISSUE TITLE
Can not program E77-400MBL-01 using clone st-link

### ISSUE THREAD

**Issue by trogalko** [olliw42/mLRS#226]
Can not program E77-400MBL-01 using two clone st-link by following the detailed step on the documentation. Is there is some tricks to be able successfully program this board with Stm32CubeProgrammer and clone st-link? while I'm awaiting my Nucleo board (with onboard stlink) to arrive?
I've done shared button click fix on Stm32CubeProgrammer, with no success

**Comment by olliw42** [comment]
@trogalko 
the github issue section is NOT for support questions. Please raise your problem in one of the discussion places, i.e., the discord channel or the rcgroups thread.
Thx for your understanding.
