### ISSUE TITLE
common_type.h POWER_24_DBM ？

### ISSUE THREAD

**Issue by suiaiyun** [olliw42/mLRS#27]
https://github.com/olliw42/mLRS/blob/ca556de7d248b888439eab5bb4744df1dce5795e/mLRS/Common/common_types.h#L38

37  POWER_23_DBM    = 24, // 200 mW
38  POWER_24_DBM    = 24, // 251 mW

Both values here are 24. Is this an error or is it the case?

**Comment by olliw42** [comment]
@suiaiyun 
ohh, that's clearly an error, POWER_23_DBM should be 23...
would you raise a PR?

**Comment by suiaiyun** [comment]
> 

Sorry, I just had time to see the message today. I've been doing flight control all weekend and forgot about this. I'm glad to see that you have fixed this problem. It's great.
