### ISSUE TITLE
Feature Request: Add hardware & version to CLI

### ISSUE THREAD

**Issue by jlpoltrack** [olliw42/mLRS#50]
Would it be possible to add the hardware & version when 'pl' (or some other) command is used?  I like that the Lua returns these two pieces of information especially with all of the updates currently being made.

![image](https://user-images.githubusercontent.com/41841496/221361837-8efa1177-cfa9-46b9-970b-de5d5c3792e0.png)

**Comment by olliw42** [comment]
good idea. I did had this wish myself before. Added cmd 'v' to cli.

**Comment by jlpoltrack** [comment]
Thanks!
