### ISSUE TITLE
Proposal | Include 24 dBm (251 mW) instead of 23 dBm (200 mW)

### ISSUE THREAD

**Issue by jlpoltrack** [olliw42/mLRS#57]
This change would affect:

- Frsky R9M
- All E28 variants

Reason - there is no 200 mW CRSF element but there is one for 250 mW.  Let me know and I can create a PR.

**Comment by olliw42** [comment]
ähm hmmm uhm ... I have no strong opinion on this ... both is fine with me. I would be interesting to get more opinons. Somehow.

**Comment by olliw42** [comment]
done
THX!!
