### ISSUE TITLE
Bug | SNR Value

### ISSUE THREAD

**Issue by jlpoltrack** [olliw42/mLRS#64]
Was looking at my EdgeTX logs and the TSNR value seems to show odd values.  When I believe that it should be a negative number it doesn't seem to be the converted correctly, example: 

![image](https://user-images.githubusercontent.com/41841496/227051010-89eb15c2-d8d1-41ba-aa64-8b1f0f0f61f7.png)

I looked through the code and I can't seem to pinpoint where this issue is.  The driver should be returning signed values: https://github.com/olliw42/sx12xx-lib/blob/main/src/sx128x.h#L105

Looks okay here too: https://github.com/olliw42/mLRS/blob/main/mLRS/Common/common_stats.h#L131

**Comment by olliw42** [comment]
I can't speak for EdgeTx, but for OpenTx it does display it positive. It's actually because CRSF uses it as positive. Watch out for the crsf_cvt_rssi() function. The driver returns it as -68, crsf as 68.

You should see that "wrong" sign with the other rssi values too.

I think this is correct.

**Comment by jlpoltrack** [comment]
I'm okay with the positive RSSI, but I think that the expected SNR values should be something like -15 to 15.  Here's the deduplicated values across the logs (I think 63 should be -1, 62 > -2, etc, offset by 64):

![image](https://user-images.githubusercontent.com/41841496/227062166-9e065f04-b7dc-47d1-999d-49c6ac84c71c.png)

**Comment by jlpoltrack** [comment]
So I think I found the issue, but let me start with why I was confused.   Per the datasheet SNR is a signed 8-bit value multiplied by 4:

![image](https://user-images.githubusercontent.com/41841496/227070689-a035df88-b066-4237-ad1a-5744b5c83a19.png)

So the SNR range should be -127 / 4 to +127 / 4 or -31 to +31 (note that values of 53 to 63 should be impossible).

This line in the module divides by 4 first then does the conversion to signed 8-bit.  It should do the conversion first then divide by 4.  https://github.com/olliw42/sx12xx-lib/blob/3e0512f6d11339bb5fcfa4c087dd0d6d2ce9ccbe/src/sx126x.cpp#L329

When I update the line to this, I get a negative SNR using stats (very helpful :) )

![image](https://user-images.githubusercontent.com/41841496/227071160-cc8533a2-4d52-492d-8c78-e49b33566953.png)

![image](https://user-images.githubusercontent.com/41841496/227071088-afad521d-678c-4176-b389-f2f222c29240.png)

Hope this makes sense

**Comment by olliw42** [comment]
interesting

a quick google gave in another driver
`( status[1] < 128 ) ? ( packetStatus->LoRa.SnrPkt = status[1] / 4 ) : ( packetStatus->LoRa.SnrPkt = ( ( status[1] - 256 ) /4 ) );`

**Comment by jlpoltrack** [comment]
That method returns the same values as my code but seems a bit complex.  Here's some comparisons with the original, my code and the version from another driver:

<img width="228" alt="image" src="https://user-images.githubusercontent.com/41841496/227140392-1db7ac46-9b8d-4df4-b5be-a0c86ff5145b.png">

**Comment by jlpoltrack** [comment]
I believe this issues exists currently in the SX128x and SX126x drivers.  The SX127x appears to do it correctly (but haven't validated this on hardware):

https://github.com/olliw42/sx12xx-lib/blob/main/src/sx127x.cpp#L322

**Comment by OptimusTi** [comment]
"Make sure to actually measure" is not a riddle. It's just a recommendation. It's the only way to make sure that the values are correct.

**Comment by olliw42** [comment]
:)
and what does the "You may find something very interesting" refer too, if I may ask?

**Comment by jlpoltrack** [comment]
Somewhat related, I don't think that RSSI for 1RSS needs to be inverted here: https://github.com/olliw42/mLRS/blob/main/mLRS/Common/common_types.cpp#L168

If I remove the inversion, EdgeTX handles 1RSS correctly (see also this note from ExpressLRS: https://github.com/ExpressLRS/ExpressLRS/blob/master/src/src/tx_main.cpp#L152)

![image](https://user-images.githubusercontent.com/41841496/227274823-8a7d7739-08f9-41ac-9f03-0d4548431d93.png)

**Comment by jlpoltrack** [comment]
Addressed with: https://github.com/olliw42/sx12xx-lib/pull/4
