### ISSUE TITLE
Feature Request | Lua | System Bootloader

### ISSUE THREAD

**Issue by jlpoltrack** [olliw42/mLRS#68]
Would it be possible to add an option in the Lua to enter the system bootloader on the Tx module?

This would be a very nice addition for Tx setups where one is primarily using the Lua for configuration and not the CLI.

**Comment by olliw42** [comment]
yes, I have that in mind (and also to add that option to the OLed display)(I really like the OLed, much easier and faster to do things than with lua script)
it will come with time :)

**Comment by olliw42** [comment]
@jlpoltrack 

I have add now the option to enter the system bootloader from the lua script. Go to Tools page.

would be great if you too could test it, just to have a second test :)

**Comment by jlpoltrack** [comment]
@olliw42 
Thanks for implementing.  Doesn't seem to work for me though.  Couple of notes:

- Maybe an EdgeTX issue?
- I haven't looked too closely but Is the mBridge command doing anything other than calling BootloaderInit() ?
- I know system bootloader is working for my hardware (DIY G4 E22) as I have implemented entering the bootloader using a switch combination using code like this: `if (rcData.ch[15] > 1200) BootLoaderInit();`

**Comment by olliw42** [comment]
hmhmhm ...

what doesn't work? 
in the lua you see the Tools option and can enter it and click the option "system bootloader", and you see the "in SYSTEM BOOT" notice showing up, but the module doesn't go into boot mode?

the mbridge command informs the oled display if there is one, and then indeed just calls BootloaderInit(). https://github.com/olliw42/mLRS/blob/main/mLRS/CommonTx/mlrs-tx.cpp#L210-L214

can you enter the systembootloader from the cli ?

I think we really need get rid of this EdgeTx issue(s) ... grrrr ... how to do that ... grrr

**Comment by olliw42** [comment]
@jlpoltrack 
maybe you happen to know
the main reason holding me back from temporarily installing EdgeTx is (besides time of course LOL) how to get fully back to OpenTx, I'm especially concerned about the bootloader.
I do have to install a new bootloader, when I go from OpenTx to EdgeTx, right? 
If so, do you happen to know how to get rid of it and get back to the original Opentx bootloader?

**Comment by jlpoltrack** [comment]
@olliw42 
> the mbridge command informs the oled display if there is one, and then indeed just calls BootloaderInit(). https://github.com/olliw42/mLRS/blob/main/mLRS/CommonTx/mlrs-tx.cpp#L210-L214

My mistake - I see now that this requires a new firmware (mbridge commands aren't in the Lua) - I will follow up today.

> I do have to install a new bootloader, when I go from OpenTx to EdgeTx, right?
If so, do you happen to know how to get rid of it and get back to the original Opentx bootloader?

I haven't confirmed myself but flashing via DFU should handles the bootloader too.  Refer to this video: https://youtu.be/PhpDf-j_3_Q?t=582

I did see this PR for EdgeTX as well that would hopefully help in future: https://github.com/EdgeTX/edgetx/pull/3411

**Comment by olliw42** [comment]
> My mistake - I see now that this requires a new firmware (mbridge commands aren't in the Lua) - I will follow up today.

yes :D

you need to update the tx firmware as well as the lua script on the radio

thx for the links, will watch

**Comment by jlpoltrack** [comment]
@olliw42 
Works with updated firmware.  Thanks!

**Comment by olliw42** [comment]
GREAT!

ufufufuf 

so I guess I can postpone another while EdgeTx efforts LOL
