### ISSUE TITLE
SX128x OTA times don't match calculator?

### ISSUE THREAD

**Issue by jlpoltrack** [olliw42/mLRS#81]
SX128x | 50 Hz shows OTA of 7892 uS but calculator shows 8128?

https://github.com/olliw42/mLRS/blob/main/mLRS/Common/sx-drivers/sx128x_driver.h#L57

![image](https://github.com/olliw42/mLRS/assets/41841496/1078e5ee-4537-4761-94e1-46bd5625e643)

SX126x matches calculator, e.g. 31 Hz:

https://github.com/olliw42/mLRS/blob/main/mLRS/Common/sx-drivers/sx126x_driver.h#L43

![image](https://github.com/olliw42/mLRS/assets/41841496/7f70bb57-a113-41cc-a5f4-bd140ac081c3)

**Comment by jlpoltrack** [comment]
Answering myself, mLRS uses the 'LI' Long Interleaving Coding Rates which align:

![image](https://github.com/olliw42/mLRS/assets/41841496/850c7c66-09f2-42d6-a2cd-c9be2d195c97)

**Comment by olliw42** [comment]
exactly!
it's the reason it uses LI. I actually wonder if not using LI would give some benefit with the crc1 mechanism, but for now it's as it is :)
