### ISSUE TITLE
Main branch fails to compile?

### ISSUE THREAD

**Issue by jlpoltrack** [olliw42/mLRS#95]
Tried to build and compile from main today:
<img width="590" alt="image" src="https://github.com/olliw42/mLRS/assets/41841496/a74c70e4-c1be-44d8-8a4f-025fbf31a33c">

Got a bunch of errors when compiling around ST drivers missing.  (I followed the usual steps with running 'run_setup.py' and had the correct workspace in STM32CubeIDE)

Had to use this commit in order to compile:

<img width="404" alt="image" src="https://github.com/olliw42/mLRS/assets/41841496/72caf45a-3b3e-4882-9435-d7c7a2cfdc72">

**Comment by olliw42** [comment]
ok

I indeed made quite substantial changes to the "build system". The main driving force is to have an aoutomated way to set compile flags.

it also gets rid of a thing which really started to massivly annoy me, namely that all the ST drivers were stored in each target (which blew up the download but also required massive comits)

can you please go to the tools folder and run run_copy_st_drivers.py. This should solve the issue, hopefully. I think the bug is that this now needs to be also called from setup.py

**Comment by jlpoltrack** [comment]
That script fails to run for me 'The system cannot find the file specified'

![image](https://github.com/olliw42/mLRS/assets/41841496/20c4cefc-e3c8-4424-9965-87a41309a985)

I do see files in that location: 
![image](https://github.com/olliw42/mLRS/assets/41841496/5aa66f96-300e-4bba-ae95-2a63d41936b2)

**Comment by olliw42** [comment]
this is not windows, right?

**Comment by jlpoltrack** [comment]
Windows 11

**Comment by olliw42** [comment]
then I'm surprised...
I was thinking that the issue are these lines https://github.com/olliw42/mLRS/blob/main/tools/run_copy_st_drivers.py#L25-L26, but they work for me, on win ...

do you maybe have to call it with python3?

**Comment by jlpoltrack** [comment]
Silly me, I had a space in my folder name 'mLRS Dev' which this script didn't like, changing to 'mLRSDev' works.

**Comment by olliw42** [comment]
great!

and not so great ... it should work with blanks ... I will check what I find on this

but it needs to be called also from run_setup, that's clearly a bug you uncovered :D

**Comment by olliw42** [comment]
it now should work

THX for discovering these issues!

**Comment by jlpoltrack** [comment]
Perfect, latest commit resolves this issue.

**Comment by olliw42** [comment]
it should also work with blanks now.

THX, this was very helpful.

**Comment by jlpoltrack** [comment]
Just confirming that it works with blanks/spaces too.

**Comment by olliw42** [comment]
:+1:
